ULMS-1075 Added cache-buster component
netology-group/ulms-components pull request #95
Opened 2021-03-22 11:50 UTC by alexkonst

2021-03-22 12:56 UTC, rogaldh requested changes

2021-03-22 12:56 UTC, rogaldh commented on packages/drawing-toolbar/package-lock.json
> -		"@ulms/ui-drawing": {
Почему-то `drawing-toolbar` затронуло

2021-03-22 14:33 UTC, rogaldh commented on package.json
> +    "bootstrap": "lerna list | sed 's/@ulms\\///g' | sed 's/ui-//g' | xargs -I{} scripts/populate-rollup.sh {} && lerna bootstrap",
Я предполагал, что для не `ui-`шных компонентов скрипт build будет свою реализацию иметь, чтобы не собирать rollupом, который лежит в рутовом пакете, но если для кешбрабоатало, то наверно это ок.
Для каких-нибудь контроллеров, возможно, стоит иметь свой специфичный срипт сборки. Надо будет поглядеть потом, как лучше

2021-03-22 14:35 UTC, rogaldh commented on packages/cache-buster/src/cache-buster.jsx
> +const refresh = () => window.location.reload()
вместо window лучше использовать globalThis, но мб стоит извне передавать функцию рефреша в компонент, чтобы в пакет не тащить.

2021-03-22 14:46 UTC, rogaldh commented on packages/cache-buster/src/utils.js
> +    // .catch(error => '')
коммент остался

2021-03-22 14:46 UTC, rogaldh commented on packages/cache-buster/src/cache-buster.jsx
> +        const versionMismatch = major || minor || patch
Мб стоит объявить константу после `if(error)`, т.к. оно все-равно будет undefined

2021-03-22 14:46 UTC, rogaldh commented on packages/cache-buster/src/cache-buster.jsx
> +          error, major, minor, patch, version,
тут переносов не хватает

2021-03-22 14:46 UTC, rogaldh commented on packages/cache-buster/src/cache-buster.jsx
> +          .then((result) => {
Может вынести обработчики в .then в отдельные методы, чтобы проще читалось?

2021-03-22 14:46 UTC, rogaldh commented on packages/cache-buster/src/cache-buster.jsx
> +      .then((result) => {
И тут тоже бы вынести

2021-03-22 15:11 UTC, alexkonst commented on packages/cache-buster/src/cache-buster.jsx
> +const refresh = () => window.location.reload()
ok

2021-03-22 15:12 UTC, alexkonst commented on packages/cache-buster/src/cache-buster.jsx
> +          error, major, minor, patch, version,
eslint не ругался

2021-03-22 15:24 UTC, alexkonst commented on packages/cache-buster/src/cache-buster.jsx
> +          .then((result) => {
ok

2021-03-25 11:10 UTC, rogaldh approved these changes

2021-03-25 11:11 UTC, rogaldh commented
Я заапрувил, но изменения в пакаджлоке тулбара остались. Это ты аудит делал?

2021-03-25 11:12 UTC, rogaldh commented
Там вроде ничего криминального, стоит отметить

2021-03-25 12:02 UTC, alexkonst commented
Убрал изменения по тулбару.

2021-03-25 12:16 UTC, merged